import React from 'react';

export const Staff =
[ 
    {
        Index: 1,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Phone: 8012345678,
    Action: 'Action',
    Edit: 'Edit',
    MaritalStatus: 'Married',
    Tittle: 'Captain',
    StaffCategory: 'Academic',
    StaffPosition: 'Senior',
    Email: 'Lady@gmail.com',
    MotherOfficeAddress: 'Federal High Sea clinic PH',
    GradeLevel: 'level 1',
    Rank: 'Rank 1',
    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',
    Signature: '',
    PrimaryInstitution: 'crist the way',
    PrimaryYeargraduated: '12/56/9864',
    FSLC: 'B+',
    FSLCertificate: '',
    SecSchool: 'Christ the way',
    SecondaryYeargraduated: '12/56/9864',
    CertBody: 'WAEC',
    NoOfSitting: 1,
    SecCertificate: '',
    SSCESubjects: [],
    SSCEGrades: [],
    TertInstitution: 'FUTO',
    TertQualification: 'B.ENG',
    GradePoint: 'Second class',
    Course: 'chemical Engineering',
    TertYeargraduated: '12/56/9864',
    TertCertificate: '',
    NYSCYear:'2019',
    NYSCCert:'',
    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAppointment: '12/45/1234',
    Sibiling: [],
    KinTitle: 'Sir',
    KinFirstName: 'Olisa',
    KinMiddleName: 'Bath',
    KinFirstName: 'Ekeh',
    KinPhoneNumber: 7012345678,
    Realationship: 'mother',
    
},

{
    Index: 2,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Phone: 8012345678,
    Action: 'Action',
    Edit: 'Edit',
    MaritalStatus: 'Married',
    Tittle: 'Captain',
    StaffCategory: 'Academic',
    StaffPosition: 'Senior',
    Email: 'Lady@gmail.com',
    MotherOfficeAddress: 'Federal High Sea clinic PH',
    GradeLevel: 'level 1',
    Rank: 'Rank 1',
    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',
    Signature: '',
    PrimaryInstitution: 'crist the way',
    PrimaryYeargraduated: '12/56/9864',
    FSLC: 'B+',
    FSLCertificate: '',
    SecSchool: 'Christ the way',
    SecondaryYeargraduated: '12/56/9864',
    CertBody: 'WAEC',
    NoOfSitting: 1,
    SecCertificate: '',
    SSCESubjects: [],
    SSCEGrades: [],
    TertInstitution: 'FUTO',
    TertQualification: 'B.ENG',
    GradePoint: 'Second class',
    Course: 'chemical Engineering',
    TertYeargraduated: '12/56/9864',
    TertCertificate: '',
    NYSCYear:'2019',
    NYSCCert:'',
    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAppointment: '12/45/1234',
    Sibiling: [],
    KinTitle: 'Sir',
    KinFirstName: 'Olisa',
    KinMiddleName: 'Bath',
    KinFirstName: 'Ekeh',
    KinPhoneNumber: 7012345678,
    Realationship: 'mother',
    
},
{
    Index: 3,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Phone: 8012345678,
    Action: 'Action',
    Edit: 'Edit',
    MaritalStatus: 'Married',
    Tittle: 'Captain',
    StaffCategory: 'Academic',
    StaffPosition: 'Senior',
    Email: 'Lady@gmail.com',
    MotherOfficeAddress: 'Federal High Sea clinic PH',
    GradeLevel: 'level 1',
    Rank: 'Rank 1',
    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',
    Signature: '',
    PrimaryInstitution: 'crist the way',
    PrimaryYeargraduated: '12/56/9864',
    FSLC: 'B+',
    FSLCertificate: '',
    SecSchool: 'Christ the way',
    SecondaryYeargraduated: '12/56/9864',
    CertBody: 'WAEC',
    NoOfSitting: 1,
    SecCertificate: '',
    SSCESubjects: [],
    SSCEGrades: [],
    TertInstitution: 'FUTO',
    TertQualification: 'B.ENG',
    GradePoint: 'Second class',
    Course: 'chemical Engineering',
    TertYeargraduated: '12/56/9864',
    TertCertificate: '',
    NYSCYear:'2019',
    NYSCCert:'',
    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAppointment: '12/45/1234',
    Sibiling: [],
    KinTitle: 'Sir',
    KinFirstName: 'Olisa',
    KinMiddleName: 'Bath',
    KinFirstName: 'Ekeh',
    KinPhoneNumber: 7012345678,
    Realationship: 'mother',
    
}
,
{
    Index: 4,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Phone: 8012345678,
    Action: 'Action',
    Edit: 'Edit',
    MaritalStatus: 'Married',
    Tittle: 'Captain',
    StaffCategory: 'Academic',
    StaffPosition: 'Senior',
    Email: 'Lady@gmail.com',
    MotherOfficeAddress: 'Federal High Sea clinic PH',
    GradeLevel: 'level 1',
    Rank: 'Rank 1',
    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',
    Signature: '',
    PrimaryInstitution: 'crist the way',
    PrimaryYeargraduated: '12/56/9864',
    FSLC: 'B+',
    FSLCertificate: '',
    SecSchool: 'Christ the way',
    SecondaryYeargraduated: '12/56/9864',
    CertBody: 'WAEC',
    NoOfSitting: 1,
    SecCertificate: '',
    SSCESubjects: [],
    SSCEGrades: [],
    TertInstitution: 'FUTO',
    TertQualification: 'B.ENG',
    GradePoint: 'Second class',
    Course: 'chemical Engineering',
    TertYeargraduated: '12/56/9864',
    TertCertificate: '',
    NYSCYear:'2019',
    NYSCCert:'',
    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAppointment: '12/45/1234',
    Sibiling: [],
    KinTitle: 'Sir',
    KinFirstName: 'Olisa',
    KinMiddleName: 'Bath',
    KinFirstName: 'Ekeh',
    KinPhoneNumber: 7012345678,
    Realationship: 'mother',
    
}
,
{
    Index: 5,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Phone: 8012345678,
    Action: 'Action',
    Edit: 'Edit',
    MaritalStatus: 'Married',
    Tittle: 'Captain',
    StaffCategory: 'Academic',
    StaffPosition: 'Senior',
    Email: 'Lady@gmail.com',
    MotherOfficeAddress: 'Federal High Sea clinic PH',
    GradeLevel: 'level 1',
    Rank: 'Rank 1',
    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',
    Signature: '',
    PrimaryInstitution: 'crist the way',
    PrimaryYeargraduated: '12/56/9864',
    FSLC: 'B+',
    FSLCertificate: '',
    SecSchool: 'Christ the way',
    SecondaryYeargraduated: '12/56/9864',
    CertBody: 'WAEC',
    NoOfSitting: 1,
    SecCertificate: '',
    SSCESubjects: [],
    SSCEGrades: [],
    TertInstitution: 'FUTO',
    TertQualification: 'B.ENG',
    GradePoint: 'Second class',
    Course: 'chemical Engineering',
    TertYeargraduated: '12/56/9864',
    TertCertificate: '',
    NYSCYear:'2019',
    NYSCCert:'',
    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAppointment: '12/45/1234',
    Sibiling: [],
    KinTitle: 'Sir',
    KinFirstName: 'Olisa',
    KinMiddleName: 'Bath',
    KinFirstName: 'Ekeh',
    KinPhoneNumber: 7012345678,
    Realationship: 'mother',
    
}
,
{
    Index: 6,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Phone: 8012345678,
    Action: 'Action',
    Edit: 'Edit',
    MaritalStatus: 'Married',
    Tittle: 'Captain',
    StaffCategory: 'Academic',
    StaffPosition: 'Senior',
    Email: 'Lady@gmail.com',
    MotherOfficeAddress: 'Federal High Sea clinic PH',
    GradeLevel: 'level 1',
    Rank: 'Rank 1',
    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',
    Signature: '',
    PrimaryInstitution: 'crist the way',
    PrimaryYeargraduated: '12/56/9864',
    FSLC: 'B+',
    FSLCertificate: '',
    SecSchool: 'Christ the way',
    SecondaryYeargraduated: '12/56/9864',
    CertBody: 'WAEC',
    NoOfSitting: 1,
    SecCertificate: '',
    SSCESubjects: [],
    SSCEGrades: [],
    TertInstitution: 'FUTO',
    TertQualification: 'B.ENG',
    GradePoint: 'Second class',
    Course: 'chemical Engineering',
    TertYeargraduated: '12/56/9864',
    TertCertificate: '',
    NYSCYear:'2019',
    NYSCCert:'',
    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAppointment: '12/45/1234',
    Sibiling: [],
    KinTitle: 'Sir',
    KinFirstName: 'Olisa',
    KinMiddleName: 'Bath',
    KinFirstName: 'Ekeh',
    KinPhoneNumber: 7012345678,
    Realationship: 'mother',
    
}


]
    


export const Students = [
    {   
         Index: 1,
    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Action: 'Action',
    Edit: 'Edit',
    FatherOccupation: 'Sailor',
    FatherTittle: 'Captain',
    MotherOfficeAddress: 'Federal High Sea PH',
    MotherOccupation: 'Nurse',
    MotherTittle: 'Lady',
    MotherOfficeAddress: 'Federal High Sea clinic PH',

    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',

    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAdmission: '12/45/1234',
    Sibiling: [],


    
},

{         Index: 2,
    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Action: 'Action',
    Edit: 'Edit',
    FatherOccupation: 'Sailor',
    FatherTittle: 'Captain',
    MotherOfficeAddress: 'Federal High Sea PH',
    MotherOccupation: 'Nurse',
    MotherTittle: 'Lady',
    MotherOfficeAddress: 'Federal High Sea clinic PH',

    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',

    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAdmission: '12/45/1234',
    Sibiling: [],


    
},

{         Index: 3,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Action: 'Action',
    Edit: 'Edit',
    FatherOccupation: 'Sailor',
    FatherTittle: 'Captain',
    MotherOfficeAddress: 'Federal High Sea PH',
    MotherOccupation: 'Nurse',
    MotherTittle: 'Lady',
    MotherOfficeAddress: 'Federal High Sea clinic PH',

    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',

    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAdmission: '12/45/1234',
    Sibiling: [],


    
},

{         Index: 4,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Action: 'Action',
    Edit: 'Edit',
    FatherOccupation: 'Sailor',
    FatherTittle: 'Captain',
    MotherOfficeAddress: 'Federal High Sea PH',
    MotherOccupation: 'Nurse',
    MotherTittle: 'Lady',
    MotherOfficeAddress: 'Federal High Sea clinic PH',

    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',

    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAdmission: '12/45/1234',
    Sibiling: [],


    
},

{
    Index: 5,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Action: 'Action',
    Edit: 'Edit',
    FatherOccupation: 'Sailor',
    FatherTittle: 'Captain',
    MotherOfficeAddress: 'Federal High Sea PH',
    MotherOccupation: 'Nurse',
    MotherTittle: 'Lady',
    MotherOfficeAddress: 'Federal High Sea clinic PH',

    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',

    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAdmission: '12/45/1234',
    Sibiling: [],


    
},

{         Index: 6,

    Photo: '',
    RegNo: 1010,
    FirstName: 'Nkechi',
    MiddleName: 'Gift',
    LastName: 'Ekeh',
    Class: 'Jss1A',
    Gender: 'Female',
    Action: 'Action',
    Edit: 'Edit',
    FatherOccupation: 'Sailor',
    FatherTittle: 'Captain',
    MotherOfficeAddress: 'Federal High Sea PH',
    MotherOccupation: 'Nurse',
    MotherTittle: 'Lady',
    MotherOfficeAddress: 'Federal High Sea clinic PH',

    FatherFirstName: 'Olisa',
    FatherMiddleName: 'Bath',
    FatherFirstName: 'Ekeh',
    FatherPhoneNumber: 7012345678,
    MotherPhoneNumber: 7012345677,
    DoctorPhoneNumber: 7012345679,
    DoctorName: 'chike Odoh',
    DoctorHospital: 'rivers clinic',
    HealthChallenges: '',
    physicalChallenges: '',

    MotherFirstName: 'Chinwe',
    MotherMiddleName: 'Glory',
    MotherLastName: 'Ekeh',
    DateOfBirth: '22/33/3333',
    HomeTown: 'Ngokpala',
    StateOfOrigin: 'Imo',
    LGAOfOrigin: 'Ngokpala',
    StaeOfResidence: 'Rivers',
    ResidentialAddress: '31 GRA PH',
    ResidentialCity: 'Port Harcout',
    Religion: 'christianty',
    Denomination: 'Catholic',
    DateOfAdmission: '12/45/1234',
    Sibiling: [],


    
}
]

export const Subject = [
    'English', 'Mathematics', 'Igbo', 'Physics','Chemistry', 'Biology'
]

export const Term = ['First Term', 'Second Term']

export const State = ['Abia', 'Adamawa', 'Akwaibom', 'Anambra']

export const Session = ['2020/2021', '2021/2022', '2022/2023']

export const Class = ['Jss1', 'Jss2', 'Jss3', 'SS1', 'SS2', 'SS3']

export const ClassSuffix = ['A','B']
export const Section = ['Primary','Secondary']